apiVersion: v1
kind: Namespace
metadata:
  name: development

# Set Quata on the Namespace
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    


