apiVersion: v1


kind: ReplicationController


metadata:
  name: webapp-rc
  labels: 
    app: web-app
    type: front-end
spec: 
  template:
    ## Pod defination from pod defination file nginx-defination.yml
    metadata:
      name: web-app
      labels:
        app: web-app
        type: frontend-app
    spec:
      containers:
        - name: webapp-container
          image: nginx
  replicas: 2
