# definations are similar to 4 except kind: Deployment
apiVersion: apps/v1
kind: Deployment

metadata:
  name: webapp-deployment
  labels: 
    app: web-app
    type: front-end
spec: 
  template:
    ## Pod defination from pod defination file nginx-defination.yml
    metadata:
      name: web-app
      labels:
        app: web-app
        type: front-end
    spec:
      containers:
        - name: webapp-container
          image: nginx:1.21.3
  replicas: 4
  selector: 
    matchLabels:
      type: front-end
