apiVersion: v1

kind: Service


metadata:
  name: myapp-service

spec:
  type: NodePort
  ports:
    - targetPort: 80    # port bound to pod
      port: 80          # Port bound to service object
      nodePort: 30008   # port bound ot Node, NodePort range is 30000 to 32767

  selector:
    app: myapp
    type: front_end
