apiVersion: v1

kind: Service


metadata:
  name: webapp-service1

spec:
  type: ClusterIP
  ports:
    - targetPort: 80    # port bound to pod
      port: 80          # Port bound to service object

  selector:
    type: front-end
