apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: blue-webapp
  name: blue-webapp-service
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30008
  selector:
    app: blue-webapp
  type: NodePort
status:
  loadBalancer: {}
