apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: blue-webapp
  name: blue-webapp
spec:
  containers:
  - image: kodekloud/webapp-conntest
    name: blue-webapp
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
