apiVersion: v1

kind: ReplicationController

metadata:
  name: myapp-rc
  labels:
    app: myapp
    name: frontend

spec:
  template:
# copied from prod defination
    metadata:
      name: myapp-pod
      labels:
        app: myapp
        type: front_end

    spec:
      containers:
      - name: nginx-container
        image: nginx 
  replicas: 3
