apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: red-webapp
  name: red-webapp-service
spec:
#  type: NodePort
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    app: red-webapp
status:
  loadBalancer: {}
