apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: red-webapp
  name: red-webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: red-webapp
  strategy: {}
  template:
    metadata:
      labels:
        app: red-webapp
    spec:
      containers:
      - image: kodekloud/simple-webapp:red
        name: simple-webapp
        resources: {}
